	CREATE TABLE CITY
	(	CITY_CODE	VARCHAR(200)	NOT NULL,
	 	CITY_NAME	VARCHAR(200)	NOT NULL
		);
	
	CREATE TABLE CUSTOMER
	(	CUSTOMER_ID VARCHAR(200)	PRIMARY KEY,
		DOB			DATE			NOT NULL,
		GENDER		VARCHAR(200),
		CITY_CODE	VARCHAR(200)
	);
	
	CREATE	TABLE	PROD_CAT_INFO
	(	PROD_CAT_CODE	VARCHAR(200)	NOT NULL,
		PROD_CAT		VARCHAR(200)	NOT NULL,
		PROD_SUB_CAT_CODE VARCHAR(200)	NOT NULL,
		PROD_SUB_CAT	VARCHAR(200)	NOT NULL
	);
	
	CREATE	TABLE	TRANSACTIONS
	(	TRANSACTION_ID	VARCHAR(200)	NOT NULL,
		CUSTOMER_ID		VARCHAR(200)	NOT NULL,
		TRAN_DATE		DATE			NOT NULL,
		PROD_SUB_CAT_CODE VARCHAR(200)	NOT	NULL,
		PROD_CAT_CODE	VARCHAR(200)	NOT	NULL,
		QTY				FLOAT			NOT NULL,
		RATE			FLOAT			NOT NULL,
		DISCOUNT		FLOAT,
		TOTAL_AMT		FLOAT			NOT NULL,
		STORE_TYPE		VARCHAR(200)
	);